# Generated by Django 2.2.1 on 2019-06-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0002_auto_20190617_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='player_of_match',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='venue',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='winner',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
