# Generated by Django 2.2.1 on 2019-06-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0003_auto_20190617_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='city',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='result',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='team1',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='team2',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='toss_decision',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='toss_winner',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
