# Generated by Django 2.2.1 on 2019-06-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0004_auto_20190617_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balls',
            name='batsman',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='balls',
            name='batting_team',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='balls',
            name='bowler',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='balls',
            name='bowling_team',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='balls',
            name='dismissal_kind',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='balls',
            name='fielder',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='balls',
            name='non_striker',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='balls',
            name='player_dismissed',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
